guava-jay/capstone

client/firebase.js, database.rules.json, package-lock.json, package.json
=> firebase connected(?)

client/components/CreateGame.js, client/store/game.js, client/store/index.js
=> set up redux store for game

client/components/CreateGame.js, client/components/Join.js, client/routes.js, client/store/game.js, server/api/game.js
=> checks in place to ensure generated slugs are unique

client/components/Room.js
=> Anon login

client/components/Room.js, client/store/game.js, client/store/user.js
=> feat: deletes anonymous players from database when they leave the page

client/components/HostView.js, client/components/PlayerView.js, client/components/Room.js
=> room separated into player/host views

client/store/user.js, server/api/game.js
=> Slug is case insensitive

client/components/HostView.js, client/components/Join.js, client/components/Room.js, script/encrypt-heroku-auth-token, server/api/game.js
=> Start button

client/components/PlayerView.js, client/components/Room.js, client/index.js, client/socket.js, package.json, schema.json, server/api/game.js, server/index.js, server/socket/index.js
=> Separate rooms

server/api/game.js, server/api/index.js, server/api/quiz.js
=> Change questions

server/api/quiz.js
=> API route PUT /api/quiz/answer now sets player's answer

client/components/Join.js
=> frontend slug case agnostic

server/api/quiz.js
=> fixed bug with answers API

client/components/HostPlaying.js, client/components/HostView.js, package-lock.json, package.json, public/codepen-embed.css, public/index.html, server/api/game.js
=> Players in host play

server/api/quiz.js
=> api/quiz/changequestion and api/quiz/answer routes now work

client/store/game.spec.js
=> 1 test added

client/components/HostPlaying.js, client/components/PlayerView.js, client/store/game.js, server/api/game.js, server/api/quiz.js
=> Host get answers

client/components/PlayerView.js
=> player view allows a redirect to home page when host closes

client/components/quiz/PlayerView.js
=> deleted prevent default on change

client/components/quiz/HostPlaying.js, client/components/quiz/PlayerView.js, client/store/game.js, server/api/quiz.js
=> fixed score display

client/components/quiz/HostPlaying.js, client/components/quiz/HostView.js, client/store/game.js, server/api/game.js, server/api/quiz.js
=> End game at ten

client/components/quiz/HostView.js
=> added missing \'i\' param in hostview, ln 78

client/components/CreateGame.js, client/components/quiz/HostView.js, client/store/game.js, server/api/game.js
=> Splitgames

client/components/Join.js, client/components/quiz/HostPlaying.js, client/components/quiz/PlayerView.js
=> Choices in host

client/components/quiz/PlayerView.js
=> Update answer confirmation

client/components/quiz/PlayerView.js, server/api/game.js
=> fix: redirect player to home page upon removal from room

client/components/quiz/HostFinished.js, client/components/quiz/HostPlaying.js, client/components/quiz/PlayerView.js, client/store/game.js, server/api/game.js
=> Sound effects

client/components/quiz/PlayerChoices.js, client/components/quiz/PlayerDisconnected.js, client/components/quiz/PlayerFinished.js, client/components/quiz/PlayerRemoved.js, client/components/quiz/PlayerView.js, client/styles/homepage.css, client/styles/index.css, client/styles/playerView.css
=> Refactor playerview

server/api/quiz.js
=> fixed up api change q route

client/components/most_likely_to/HostPlaying.js, client/store/game.js
=> merge conflict

client/components/HostView.js, client/styles/hostView.css
=> fixed thing

client/components/HostView.js, client/store/user.js
=> MLT can't start until 2 players have joined

client/components/CreateGame.js
=> minor fix to hostview
